### PR TITLE
Review code iter

### PR DESCRIPTION
**Pull request by tafia**
Another review: codeiter
It mostly improves readability (to me at least), most of the logic hasn't changed, except for macros declaration.
- iterators instead of while
- matches instead of ifs
- remove several StmtIndicesIter members

I also added a bench to compare. On my system there is a mere 4% improvement, nothing significant but at least it is not worse.

I think a 'merge' between codeiter and codecleaner might be possible to avoid reading the src twice, i don't know yet all the impacts so i'll see for it later.

Again, let me know.

### CODE REVIEW

**Comment by phildawes** [comment]
Hi @tafia ,
I like the simplified code, thanks! Unfortunately this breaks a bunch of the unit tests (e.g. do a 'cargo test')

**Comment by tafia** [comment]
Can you give me some examples ?
All but the same 4 tests work fine on my side.
I'm sorry for wasting your time ...

**Comment by phildawes** [comment]
Hi @tafia 
No worries. It's probably something to do with the merge - your branch is a few commits behind now.
I get
failures:
    racer::ast::ast_sandbox
    racer::codeiter::iterates_half_open_subscope_if_is_the_last_thing
    racer::codeiter::iterates_inner_scope
    racer::codeiter::iterates_macro
    racer::codeiter::iterates_macro_invocation
    racer::codeiter::iterates_module_attribute
    racer::codeiter::iterates_single_use_stmts
    racer::codeiter::iterates_use_stmt_over_two_lines
    racer::codeiter::iterates_use_stmt_without_the_prefix
    racer::test::completes_local_scope_let
    racer::test::completes_struct_field_via_assignment
    racer::test::completes_via_parent_scope_let
    racer::test::destructures_a_tuplestruct
    racer::test::destructures_a_tuplestruct_with_generic_arg
    racer::test::differentiates_type_and_value_namespaces
    racer::test::finds_a_generic_retval_from_a_function
    racer::test::finds_definition_of_lambda_argument
    racer::test::finds_defn_of_struct_field
    racer::test::finds_field_type
    racer::test::finds_glob_imported_enum_variant
    racer::test::finds_impl_fn
    racer::test::finds_inline_fn
    racer::test::finds_templated_impl_fn
    racer::test::finds_type_of_tuple_member_in_fn_arg
    racer::test::finds_type_of_tuple_member_via_fn_retval
    racer::test::finds_type_of_tuple_member_via_let_expr
    racer::test::finds_type_of_tuple_member_via_let_type
    racer::test::follows_arg_to_enum_method
    racer::test::follows_arg_to_method
    racer::test::follows_chained_method_call
    racer::test::follows_fn_to_method
    racer::test::follows_let_method_call
    racer::test::follows_self_to_method
    racer::test::follows_self_to_method_when_call_on_new_line
    racer::test::follows_self_use
    racer::test::follows_use
    racer::test::follows_use_as
    racer::test::follows_use_glob
    racer::test::follows_use_to_impl
    racer::test::follows_use_to_inline_mod
    racer::test::gets_type_via_match_arm
    racer::test::handles_an_enum_option_style_return_type
    racer::test::handles_if_let
    racer::test::handles_if_let_as_expression
    racer::test::uses_generic_arg_to_resolve_trait_method

test result: FAILED. 49 passed; 45 failed; 2 ignored; 0 measured

**Comment by tafia** [comment]
OK thanks !
Doing it asap

**Comment by tafia** [comment]
There was indeed a typo error.
Fixed.
PS: I cannot update my rust version because of some curl issue i have, so i couldn't rebase.

**Comment by phildawes** [comment]
Thanks! I'll hopefully get some time to test it more and look through it thoroughly later today
Have a good weekend!

**Comment by tafia** [comment]
Thanks !
It's already saturday night here :)
I am having a look at other files. Next target might be scope.rs, others
look too impressive for now :)
It is like a puzzle, I'm leaning piece after piece. I will probably add
more functions comments once I grab it all, it'll help next guys !
Have a good week end too.

**Comment by tafia** [comment]
I don't want to push new changes if i am in the wrong direction so I prefer waiting for your feedack.
Fyi, I have reviewed scope as well. There are very good results for mask_comment and mask_sub_scopes.

**Comment by tafia** [comment]
Nice !
Thanks

**Comment by phildawes** [comment]
Thanks @tafia. Sorry I've been dragging my heels a bit lately - my evenings are a bit busy at the moment.

**Pull request merged**
