### PR TITLE
Review scope

### PR DESCRIPTION
**Pull request by tafia**
Review scope.rs.
More match and iter, less 'return'.
Improved mask_comment and mask_sub_scope (40% better in benches).

### CODE REVIEW

**Comment by phildawes** [comment]
Hi @tafia,

This looks great, thanks for spending the time.

For me the jury is still out on the return vs no-return changes. I leave out return for functional one-liners, but when there are lots of lines in a function I find 'return' easier on the eye. Do you know if there are any rust guidelines or discussion on the subject?

I'll do some testing and then merge this tonight

Cheers,

Phil

**Comment by phildawes** [comment]
I found this on HN, which agrees with your patch (no-unnecessary-return-at-the-end style)
https://news.ycombinator.com/item?id=8980516

**Comment by tafia** [comment]
OK indeed
It just feel more rust and I got used to it.
But I have no strong opinion on this particular point

**Comment by tafia** [comment]
Rebased and removed some warnings with latest rust

**Comment by phildawes** [comment]
D'oh! In my head I'd already merged this. Sorry, will do this tonight

**Comment by tafia** [comment]
It's really OK !
It is less important than breaking changes or new functionalities
integrated since then.
And I rode your message on racer update 4 ...
Thanks for the last paragraph !

**Comment by tafia** [comment]
Rebased again and added black_box for more honest benches

**Comment by phildawes** [comment]
Thanks!

**Pull request merged**
