### PR TITLE
Update racer.el

### PR DESCRIPTION
**Pull request by marsam**
Hi:

I've updated the `racer.el` package, to use `deferred.el` and separate the company-package to use `racer.el`. I think this change will simplify things like adding support for auto-complete (#313)

If this get merged I think the melpa recipe of `company-racer` can be updated to use this package.

Thanks in advance.

### CODE REVIEW

**Comment by dleslie** [comment]
It would be nice if ```racer--complete-at-point-fn`` remained in some capacity, so that those not using ``company-mode`` specifically can tie it into Emacs' built-in ``completion-at-point-functions``.

In fact, IMHO Racer ought to tie into ``completion-at-point-functions`` by default, with ``company`` or other as optional extensions.

**Comment by marsam** [comment]
I totally agree about `racer--complete-at-point-fn`. I'll update the pull request this weekend

**Comment by dleslie** [comment]
Cool! Thank-you

**Comment by dleslie** [comment]
Any news @marsam? :smile:

**Comment by dleslie** [comment]
Given the discussion in #252 perhaps it is appropriate that this pull request be abandoned?

**Comment by marsam** [comment]
Hi, I sorry for the late response, I was really busy these days :(. I'll close this pull request for now and follow the discussion.

**Pull request closed without merging**
