### PR TITLE
Fix searching enum definition in match arm

### PR DESCRIPTION
**Pull request by tafia**
When testing #273, I encountered an issue in `search_scope_headers`.
We can early return in case we are in the enum part of the match arm.

Added a test which doesn't work on current master

### CODE REVIEW

**Comment by tafia** [comment]
Just see the commits, I can rebase on master so it'll look better if needed.

**Comment by phildawes** [comment]
Hi @tafia. This looks good, thanks! If you could rebase that would be great

**Comment by tafia** [comment]
sure, I'll do this asap

**Comment by phildawes** [comment]
Hi @tafia. Thanks again, I rebased your fix onto master.

**Comment by tafia** [comment]
Sorry !
I should have done it. Very sorry !

**Comment by phildawes** [comment]
No worries, thanks for the fix!

**Pull request closed without merging**
