### PR TITLE
Show type information for field completions

### PR DESCRIPTION
**Pull request by Manishearth**
fixes https://github.com/jwilm/racerd/issues/26

Might want to accompany this with a version bump and publish since racerd wants to use it.

r? @phildawes

### CODE REVIEW

**Comment by Manishearth** [comment]
Screenshot of it working:

screenshot from 2016-02-05 04 42 10

Note that non scalar primitive types do not show up properly. On completing the following code:

```rust
struct Foo<'a> {
 reference: &'a u8,
 array: [u8; 5],
 slice: &'a [u8],
}

fn foo(x: Foo) {
 x.
}
```

the following completions show up. We might want to add a TyPrimitive to handle `&T`, `&[T; N]` and `&[T]` (not sure if we should attempt to work with function types).

screenshot from 2016-02-05 04 45 19

**Comment by phildawes** [comment]
Awesome work, thanks @Manishearth

**Comment by jwilm** [comment]
Huzzah! :100:

**Comment by phildawes** [comment]
(Will do the racer release tonight when I get home)

**Pull request merged**
