### PR TITLE
specify versions of dependencies

### LINKED ISSUE #459: incompatibility with syntex_syntax v0.25.0
Hi! Arch Linux is in use. The error takes place:
```txt
~ $ cargo install racer
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling libc v0.2.4
   Compiling winapi-build v0.1.1
   Compiling unicode-xid v0.0.3
   Compiling bitflags v0.3.3
   Compiling winapi v0.2.5
   Compiling strsim v0.4.0
   Compiling ansi_term v0.7.1
   Compiling regex-syntax v0.2.2
   Compiling vec_map v0.4.0
   Compiling rustc-serialize v0.3.16
   Compiling log v0.3.4
   Compiling kernel32-sys v0.2.1
   Compiling memchr v0.1.7
   Compiling aho-corasick v0.4.0
   Compiling typed-arena v1.1.0
   Compiling term v0.2.14
   Compiling clap v1.5.5
   Compiling regex v0.1.46
   Compiling env_logger v0.3.2
   Compiling toml v0.1.25
   Compiling syntex_syntax v0.25.0
   Compiling racer v1.1.0
.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.1.0/src/racer/ast.rs:44:17: 44:27 error: mismatched types:
 expected `syntex_syntax::errors::DiagnosticBuilder<'_>`,
    found `syntex_syntax::errors::FatalError`
(expected struct `syntex_syntax::errors::DiagnosticBuilder`,
    found struct `syntex_syntax::errors::FatalError`) [E0308]
.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.1.0/src/racer/ast.rs:44             Err(FatalError) => None
                                                                                                ^~~~~~~~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.1.0/src/racer/ast.rs:44:17: 44:27 help: run `rustc --explain E0308` to see a detailed explanation
.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.1.0/src/racer/ast.rs:56:17: 56:27 error: mismatched types:
 expected `syntex_syntax::errors::DiagnosticBuilder<'_>`,
    found `syntex_syntax::errors::FatalError`
(expected struct `syntex_syntax::errors::DiagnosticBuilder`,
    found struct `syntex_syntax::errors::FatalError`) [E0308]
.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.1.0/src/racer/ast.rs:56             Err(FatalError) => {
                                                                                                ^~~~~~~~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.1.0/src/racer/ast.rs:56:17: 56:27 help: run `rustc --explain E0308` to see a detailed explanation
.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.1.0/src/racer/snippets.rs:61:21: 61:31 error: mismatched types:
 expected `syntex_syntax::errors::DiagnosticBuilder<'_>`,
    found `syntex_syntax::errors::FatalError`
(expected struct `syntex_syntax::errors::DiagnosticBuilder`,
    found struct `syntex_syntax::errors::FatalError`) [E0308]
.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.1.0/src/racer/snippets.rs:61                 Err(FatalError) => {
                                                                                                         ^~~~~~~~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/racer-1.1.0/src/racer/snippets.rs:61:21: 61:31 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 3 previous errors
failed to compile `racer v1.1.0`, intermediate artifacts can be found at `/home/anli/target-install`

Caused by:
  Could not compile `racer`.

To learn more, run the command again with --verbose.
~ $ rustc -V
rustc 1.5.0
~ $ cargo -V
cargo 0.7.0 (1af03be 2015-12-08)
```
How to cure?

### PR DESCRIPTION
**Pull request by lukesteensen**
Should fix #459

### CODE REVIEW

**Comment by jaxx** [comment]
There's no need for specifying version in toml file. Version is already locked in lock file. In #459 users who got this problem, ran ´´´cargo update´´´ command, which updates lock file. Racer made compatible with syntex_syntax 0.25.0 in #461

**Comment by lukesteensen** [comment]
@jaxx The issue is that the lock file doesn't seem to be respected when racer is built through `cargo install`. There was no `cargo update` involved.

**Comment by lukesteensen** [comment]
The real issue may be with `cargo install` here, but this seemed like a simple fix that could get `cargo install racer` working again. It's also my understanding that specifying versions of your dependencies is a best practice.

**Comment by jaxx** [comment]
That's strange that ````cargo install``` tries to download and compile newest libraries. I never used ```cargo install``` myself and hadn't clue about this behaviour.

**Comment by lukesteensen** [comment]
Yes this was the first time I tried it and was very surprised to see it fail when I knew racer built fine otherwise. I agree with merging #461, but it does seem like we need to specify this to avoid issues in the future.

**Comment by jaxx** [comment]
Yup, you're right. Maybe you also specify all the versions of dependencies then?

**Comment by lukesteensen** [comment]
That's a good idea, I can go ahead and add another commit.

**Comment by jaxx** [comment]
(Y)

**Comment by jaxx** [comment]
And it's a bug https://users.rust-lang.org/t/cargo-install-and-lock-file/4203

**Comment by phildawes** [comment]
@jaxx, @lukesteensen Sorry I'm late to this discussion. Cargo install ignoring the lock files is a big problem, thanks for following this up @jaxx. I guess we should merge this now, and then switch back to relying on lock files when this gets fixed?

**Comment by jaxx** [comment]
@phildawes I agree!

**Comment by lukesteensen** [comment]
@phildawes Sounds good to me!

**Pull request merged**
