### PR TITLE
Fix #330 use tempname() instead of racertmp

### LINKED ISSUE #330: Make a Vim variable that allows users to set the path of the tmp file
I would like to be able to override the path of where the racertmp files get written.

E.g. Instead of the current directory, a user could point to `/tmp` as the default

### PR DESCRIPTION
**Pull request by Shougo**
I fixed #330 problem.
Please check it.

### CODE REVIEW

**Comment by phildawes** [comment]
@Shougo, this looks awesome. I'll give it a quick run-through tonight or tomorrow and then merge.  Thanks!

**Comment by Shougo** [comment]
:-)

**Comment by phildawes** [comment]
Hi @shougo,

Sorry for the delay in reviewing the patch. I'm afraid I don't think this works as is: The main reason the existing plugin writes the temp file in the same directory is so that racer can find the other modules, Cargo.toml etc.. from the file position. Unfortunately after this patch racer fails to find other local modules because it searches as if they are in the /tmp directory.

E.g. Open racer/src/bin/main.rs in vim and then try to 'gd' on a function reference. (e.g. go to line 20, col 25, hit 'gd' to go to 'do_file_search'). 

Luckily racer has recently added functionality to support tempfiles in a different directory: The patch needs to pass the original filename to racer, but then can pass the temporary filename as an additional arg.

My vim is pretty rubbish, but I guess this will be:

```
     let cmd = g:racer_cmd." complete ".line(".")." ".col." ".fname." ".tmpfname
```

Hope that makes sense,

Phil

**Comment by Shougo** [comment]
@phildawes Thank you.  Fixed.

**Comment by phildawes** [comment]
I gave it a quick test, looks good. Thanks!

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
