### PR TITLE
Emacs: Error if no definition is found

### PR DESCRIPTION
**Pull request by fbergroth**
Better than being silent.

### CODE REVIEW

**Comment by syohex** [comment]
I suppose `message` is better than `error` in such case.

**Comment by fbergroth** [comment]
`error` seems to be more common, such as in [elpy](https://github.com/jorgenschaefer/elpy/blob/ea71a12822207391010ab02de778808179b42e41/elpy.el#L1594) and [elisp-slime-nav](https://github.com/purcell/elisp-slime-nav/blob/f6d241b11abbc4064e17e02dbd0bc6c61db256cc/elisp-slime-nav.el#L100). I guess it's easier to handle if you want to call `racer-find-definition` from elisp.

**Comment by syohex** [comment]
I see

**Comment by phildawes** [comment]
Thanks @fbergroth

**Pull request merged**
