### PR TITLE
Emacs: Bind M-, to pop-tag-mark

### LINKED ISSUE #375: emacs racer-mode:  need  `racer-pop-mark`
same to `cscope-pop-mark`

### PR DESCRIPTION
**Pull request by fbergroth**
Closes #375.

### CODE REVIEW

**Comment by moonlite** [comment]
Hm, why? `pop-tag-mark` is bound to `M-*` by default.

**Comment by tomjakubowski** [comment]
I just ran `emacs -nw -q` and `M-,` was bound to `xref-pop-marker-stack` and nothing was bound to `M-*`.

**Comment by moonlite** [comment]
@tomjakubowski `M-,` is bound to `tags-loop-continue` here (I'm on 24.5.1). Are you on unstable?

**Comment by tomjakubowski** [comment]
As a matter of fact, I am.

**Comment by birkenfeld** [comment]
Can confirm that on Emacs 25, `M-,` is bound to `xref-pop-marker-stack`. Since racer find-definition only jumps to a single target, I think it makes more sense for previous versions too, so :+1: for the PR.

**Comment by fbergroth** [comment]
It's just a convenience for Emacs24 users. A lot of packages adds this particular binding, so Emacs24 users may expect it to work in racer as well.

**Comment by phildawes** [comment]
Thansk @fbergroth, applied.

**Pull request merged**
