### PR TITLE
Depend on `syntex_syntax` rather than `syntax`

### PR DESCRIPTION
**Pull request by tamird**
Probably won't solve #202 due to https://github.com/erickt/rust-syntex/issues/2

### CODE REVIEW

**Comment by tamird** [comment]
Yeah, this is green on nightly but not beta due to https://github.com/erickt/rust-syntex/issues/2

**Comment by phildawes** [comment]
Hi @tamird,

Thanks very much for working on this. I'm thinking this should go in a separate 1.0 branch rather than master due to the increase in build times, what do you think?

Cheers,

Phil

**Comment by tamird** [comment]
@phildawes yikes, the difference is build time is indeed surprising. I'm hesitant to put things in a separate branch, but maybe it's okay to not merge this until after 1.0 is out and `syntex` works for real.

**Comment by erickt** [comment]
fyi, syntex v0.4.0 now compiles with beta :)

**Comment by phildawes** [comment]
Oh nice work @erickt. In that case we should probably merge with master now that we have a real shot at a 1.0 compatible racer.

**Comment by tamird** [comment]
Yeah I'm working on getting this building successfully on 1.0 now.

**Comment by phildawes** [comment]
Merged!

**Pull request closed without merging**
