### PR TITLE
Add deoplete source

### PR DESCRIPTION
**Pull request by Shougo**
Hi, I added deoplete source for racer.
You can complete candidates in deoplete.

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Does this pull-request mean Deolete's completion interface is stable now?

**Comment by Shougo** [comment]
The interface is almost stable.
But it may be changed later.
If it is changed, I will change the source.

**Comment by leonardinius** [comment]
I've tried this PR locally. Works like a charm. Thanks.

**Comment by phildawes** [comment]
Cool - added!

**Pull request merged**
