### PR TITLE
implement getting signature of function

### PR DESCRIPTION
**Pull request by krzat**
I'm trying to implement feature from issue #41.

This is not ready yet, I just wanted to ask something. I used find_definition_ to get declaration of the requested function, but in the complex case on the test, the contextstr is
"pub fn string_to_parser<'        'a ParseSess, source_str: String) -> Parser<'"
so few chars at the end are missing. 

Is this a bug of the find_definition_ function?

### CODE REVIEW

**Comment by krzat** [comment]
Nevermind, I could do this without find_definition_ (assuming supplied coordinates point at declaration already, which should happen if racer was used to get them).

**Comment by phildawes** [comment]
Hi @krzat. I don't know sublimetext (I code rust in emacs), Can you use another key to trigger function signature getting? E.g. in intellij you use ctrl-p to get arguments

**Comment by krzat** [comment]
I could probably do that, but pressing Ctrl+P every time user calls
function isn't very convenient. I will try observing '(' press and
determining if its function call,but its still not as good as inserting it
at the completion, IMO.

I was asking about JSON, because it would be easier to bake additional data
like this without breaking anything.

2015-02-02 7:15 GMT+01:00 Phil Dawes <notifications@github.com>:

**Comment by krzat** [comment]
Anyway, the functionality from #41 seems to be achieved (except I added NAME to return name of the function too), so it's ready to merge (unless you have some problems with the code).

**Comment by krzat** [comment]
closing for now, it won't work properly across files

**Pull request closed without merging**
